name: Deploy to AKS (stg)

on:
  pull_request:
    branches: [ main ]

jobs:
  call-container-build-workflow:
    uses: ./.github/workflows/container-build.yaml
    with:
      container-tag: latest-stg
      build-stage: stg
    secrets: inherit
  kustomize:
    needs: call-container-build-workflow
    uses: ./.github/workflows/kustomize.yaml
    with:
      build-stage: stg
    secrets: inherit