name: Deploy to AKS (dev)

on:
  push:
    branches-ignore: [ main, next ]
  pull_request:
    branches-ignore: [ main, next ]

jobs:
  call-container-build-workflow:
    uses: ./.github/workflows/container-build.yaml
    with:
      container-tag: latest-dev
      build-stage: dev
    secrets: inherit
  kustomize:
    needs: call-container-build-workflow
    uses: ./.github/workflows/kustomize.yaml
    with:
      build-stage: dev
    secrets: inherit