name: Deploy to AKS (main)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  call-container-build-workflow:
    uses: ./.github/workflows/container-build.yaml
    with:
      container-tag: latest
      build-stage: prod
    secrets: inherit